import * as I from "../assets/index.js";
export const inputData = [
  {
    icon: I.UserIconForm,
    alt: "User Icon",
    placeholder: "Username",
    type: "text",
  },
  {
    icon: I.EnvelopeIconForm,
    alt: "Email Icon",
    placeholder: "Email Address",
    type: "email",
  },
  {
    icon: I.LockKeyIconForm,
    alt: "Password Icon",
    placeholder: "Password",
    type: "password",
  },
  {
    icon: I.LockKeyIconForm,
    alt: "Confirm Password Icon",
    placeholder: "Confirm Password",
    type: "password",
  },
];

export const cardsData = [
  {
    image: I.MagicMushroom,
    alt1: "mushroom",
    title: "Magic Mushroom 0325",
    avatar: I.Shroomie,
    alt2: "avatar shroomie",
    nickname: "Shroomie",
  },
  {
    image: I.HappyRobot032,
    alt1: "happy robot 1",
    title: "Happy Robot 032",
    avatar: I.Bekind2Robots,
    alt2: "avatar BeKind2Robots",
    nickname: "BeKind2Robots",
  },
  {
    image: I.HappyRobot024,
    alt1: "happy robot 2",
    title: "Happy Robot 024",
    avatar: I.Bekind2Robots,
    alt2: "avatar BeKind2Robots",
    nickname: "BeKind2Robots",
  },
  {
    image: I.DesignerBear,
    alt1: "designer bear",
    title: "Designer Bear",
    avatar: I.MrFox,
    alt2: "avatar MrFox",
    nickname: "Mr Fox",
  },
  {
    image: I.ColorFulDog0356,
    alt1: "colorful dog 1",
    title: "Colorful Dog 0356",
    avatar: I.Keepitreal,
    alt2: "avatar Keepitreal",
    nickname: "Keepitreal",
  },
  {
    image: I.DancingRobot0312,
    alt1: "dancing robot",
    title: "Dancing Robot 0312",
    avatar: I.Robotica,
    alt2: "avatar Robotica",
    nickname: "Robotica",
  },
  {
    image: I.CherryBlossomGirl035,
    alt1: "cherry blossom girl",
    title: "Cherry Blossom Girl 035",
    avatar: I.MoonDancer,
    alt2: "avatar MoonDancer",
    nickname: "MoonDancer",
  },
  {
    image: I.SpaceTravel,
    alt1: "space travel",
    title: "Space Travel",
    avatar: I.NebulaKid,
    alt2: "avatar NebulaKid",
    nickname: "NebulaKid",
  },
  {
    image: I.SunsetDimension,
    alt1: "sunset dimension",
    title: "Sunset Dimension",
    avatar: I.Animakid,
    alt2: "avatar Animakid",
    nickname: "Animakid",
  },
  {
    image: I.DesertWalk,
    alt1: "desert walk",
    title: "Desert Walk",
    avatar: I.Catch22,
    alt2: "avatar Catch22",
    nickname: "Catch 22",
  },
  {
    image: I.IceCreamApe0324,
    alt1: "icecream ape",
    title: "IceCream Ape 0324",
    avatar: I.IceApeClub,
    alt2: "avatar IceApeClub",
    nickname: "Ice Ape Club",
  },
  {
    image: I.ColorfulDog0344,
    alt1: "colorful dog 2",
    title: "Colorful Dog 0344",
    avatar: I.PuppyPower,
    alt2: "avatar PuppyPower",
    nickname: "PuppyPower",
  },
];

export const collectionsData = [
{
  image1: I.DogCollections,
  image2: I.CatCollections,
  image3: I.BearCollections,
  title: "DSGN Animals",
  avatar: I.MrFox,
  nickname: "MrFox",
},
{
  image1: I.Mushrooms1Collections,
  image2: I.Mushrooms2Collections,
  image3: I.Mushrooms3Collections,
  title: "Magic Mushrooms",
  avatar: I.Shroomie,
  nickname: "Shroomie",
},
{
  image1: I.Robot1Collections,
  image2: I.Robot2Collections,
  image3: I.Robot3Collections,
  title: "Disco Machines",
  avatar: I.Bekind2Robots,
  nickname: "BeKind2Robots",
},
{
  image1: I.DogCollections,
  image2: I.CatCollections,
  image3: I.BearCollections,
  title: "DSGN Animals",
  avatar: I.MrFox,
  nickname: "MrFox",
},
{
  image1: I.Mushrooms1Collections,
  image2: I.Mushrooms2Collections,
  image3: I.Mushrooms3Collections,
  title: "Magic Mushrooms",
  avatar: I.Shroomie,
  nickname: "Shroomie",
},
{
  image1: I.Robot1Collections,
  image2: I.Robot2Collections,
  image3: I.Robot3Collections,
  title: "Disco Machines",
  avatar: I.Bekind2Robots,
  nickname: "BeKind2Robots",
},
{
  image1: I.DogCollections,
  image2: I.CatCollections,
  image3: I.BearCollections,
  title: "DSGN Animals",
  avatar: I.MrFox,
  nickname: "MrFox",
},
{
  image1: I.Mushrooms1Collections,
  image2: I.Mushrooms2Collections,
  image3: I.Mushrooms3Collections,
  title: "Magic Mushrooms",
  avatar: I.Shroomie,
  nickname: "Shroomie",
},
{
  image1: I.Robot1Collections,
  image2: I.Robot2Collections,
  image3: I.Robot3Collections,
  title: "Disco Machines",
  avatar: I.Bekind2Robots,
  nickname: "BeKind2Robots",
},
];

